# Generated by Django 5.0.6 on 2025-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISSUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('serial_no', models.CharField(max_length=15)),
                ('customer', models.CharField(max_length=50)),
                ('machine', models.CharField(choices=[('AOI', 'AOI'), ('AXI', 'AXI'), ('ICT', 'ICT')], max_length=3)),
                ('model', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('progress', models.TextField()),
                ('executor', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('on going', 'ON GOING'), ('closed', 'CLOSED')], default='ON GOING', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOAN PART', 'LOAN PART')], default='MEDIUM', max_length=15, null=True)),
            ],
        ),
    ]
